resolver: nightly-2025-04-02
packages:
  - .

extra-deps:
  - rest-rewrite-0.4.3
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - store-0.7.19
  - store-core-0.4.4.6
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 6baa675f6bb000d016f0c859d7f865263679dc43 
    subdirs:
      - .
      - liquid-prelude
      - liquid-vector
      - liquidhaskell-boot
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 031df812a6df0c05b675ac1db9a9076f38b1c6e8 

allow-newer: true
nix:
  pure: true
  enable: true
  packages: [cacert, git, hostname, z3]
